### ISSUE TITLE
Add in vendors email

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-service#109]
The email address at the top of the email is the _vendors_ email address. So let's add that in payments-config and the emails...

**Comment by brampitoyo** [comment]
Yes. Similar to this reference design, where vendor email appears below vendor name:

![fxa payments - receipt failed](https://cloud.githubusercontent.com/assets/51007/8739589/ae6d95a4-2c91-11e5-8a2d-284395563bec.png)
