### ISSUE TITLE
Return all subscriptions in response to a subscription change request

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/payments-service#132]
See http://payments-service.readthedocs.org/en/latest/topics/api.html#post--api-braintree-subscriptions-paymethod-change-

It doesn't currently return anything. Is it easier to return the subs post-change or modify the state with the new payMethod directly.

**Comment by andymckay** [comment]
What would you prefer?

**Comment by muffinresearch** [comment]
So as discussed in irc - for now we should just do a GET. Later if it's a problem we can optimize out the GET by returning direct in response to the update.

**Comment by kumar303** [comment]
Also, there might be complications in returning subscriptions from the change method if we need to paginate the list of subscriptions.

**Comment by muffinresearch** [comment]
> Also, there might be complications in returning subscriptions from the change method if we need to paginate the list of subscriptions. 

Good point.

**Comment by muffinresearch** [comment]
Let's reopen if we need it.
