### ISSUE TITLE
Allow email only buyers to login to the management interface

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-service#142]
If a buyer has purchased something and given us an email, then they are classed in solitude as unverified and can't log in to the management interface.

However if they go to Firefox Accounts and create an account (or just login) and the email address is the same as the one that exists in solitude.... then we can update their account in solitude and they become verified.

At that point they can log in to the management interface just like anyone else.

If there's any questions @washort did this for the Marketplace.

Supports: https://github.com/mozilla/payments/issues/117

**Comment by kumar303** [comment]
this will get fixed by https://github.com/mozilla/payments-service/issues/149
