### ISSUE TITLE
Store buyer resource_pk not UUID in session

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#22]
It would be nice to store the buyer's resource_pk after login, not the UUID. It seems like the resource_pk is more useful for lookups.

**Comment by andymckay-limited-access** [comment]
I wrote some of the solitude APIs as accepting the UUID because I thought that would simpler for the service to interact with. Happy to move those to resource_pk or whatever value you would like to make it easier for the service.

**Comment by kumar303** [comment]
You can't filter a braintree customer by UUID which is why I filed this https://solitude.readthedocs.org/en/latest/topics/braintree.html#get--braintree-mozilla-buyer- We could fix that one filter but there might be other things that come up so I was thinking maybe storing `{buyer_uuid: ..., buyer_pk: ...}` in the session would be more flexible.

**Comment by andymckay** [comment]
Easy enough to add the filter. Whatever keeps payments-service simple. Let me know.
