### ISSUE TITLE
Prevent user from clicking Subscribe button twice

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#25]
We should see if we can make something server side that catches and prevents the UI from submitting the same subscribe request twice. Maybe this is something we can do only in the UI, I'm not sure.

**Comment by muffinresearch** [comment]
Fwiw - braintree has dupe detection too.

**Comment by kumar303** [comment]
By commenting out the code that disables the submit button I was able to subscribe twice in a row. I think braintree is generating a new nonce but this is still something we should probably protect against. It may be unlikely since the user would have to monkey with JavaScript (I suppose) but seems worth a try.

**Comment by kumar303** [comment]
My current plan is to do a Solitude query to see if the user is already subscribed to the product. This should prevent any duplicate subscriptions. Depends on https://github.com/mozilla/solitude/issues/456

**Comment by muffinresearch** [comment]
Yep, we should still do our own solution. Fwiw the duplication detection stuff might only work if the appropriate setting is turned on.
