### ISSUE TITLE
Figure out a users email address

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-service#35]
We'll need to be able to send users an email. There's a receipt upon completion of a payment flow. But then there are emails to be sent later on when subscriptions complete.

Currently we get the access token and FxA id in the flow, hash it and store that value. We don't have their email.

How do we get their email? From the access token, ask for and then store a refresh token in solitude? Dunno.

**Comment by kumar303** [comment]
Looks like we just need a properly scoped token for this.

Here is another issue for some enforcement of this: https://github.com/mozilla/payments-service/issues/40
