### ISSUE TITLE
Consume product information

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/payments-service#44]
Consume product information from mozilla/payments-config. So that we don't need to do as many look ups.

This is a speculative bug based on all the things we said we'd stick in here.

What does payments-service need in payments-config?

**Comment by kumar303** [comment]
I'm not sure if we need anything. The UI will pass us a plan ID per product. Maybe we need to do validation to make sure the plan ID is valid? Maybe not because Solitude does that already.

**Comment by kumar303** [comment]
I vote for not adding this to the service. Re-open if I'm missing something. I think we should rely on solitude to do the plan ID validation. If we put it in the service we'll need to keep the payments-config updated which is maintenance that seems worthwhile to avoid.
