### ISSUE TITLE
Post buyer email address upon creation

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#54]
We are [requiring email addresses](https://github.com/mozilla/payments-service/pull/43) in FxA tokens but we also need to store that in Solitude when posting to create the buyer objects.

Required for https://github.com/mozilla/payments/issues/64

**Comment by andymckay** [comment]
Is there a way we can avoid storing it?
- so that we don't have PII data around for when we get hacked
- so that users can change their email address in one place and we aren't out of sync?

**Comment by kumar303** [comment]
Well, emails are encrypted so at least there's that. I think the only way to do it is to store the oauth token but that has other implications.

**Comment by kumar303** [comment]
actually, due to the expiry of tokens I'm not sure we can do only that

**Comment by kumar303** [comment]
Yeah, I think we need refresh tokens (which can be stored indefinitely) to be able to look up the email each time: https://github.com/mozilla/fxa-oauth-server/issues/209 However, if we store an access token in Solitude that is the key to a payment which means a stolen token could be used to masquerade as an authenticated user. 

The feature for changing emails also hasn't landed yet: https://github.com/mozilla/fxa-auth-server/issues/957

**Comment by kumar303** [comment]
We decided to revisit storing emails (and hopefully stop storing them) at a later date, maybe when FxA lands some support for email lookups. Rumor on `#fxa` says this will happen.

**Comment by kumar303** [comment]
tracking this use case here: https://github.com/mozilla/fxa-auth-server/issues/962

Scratch what I said about the access/refresh token. That option is off the table because the access token will soon be short lived. We won't have access to the _refresh_ token because that is protected by the 3rd party who sent us the access token.
