### ISSUE TITLE
Provide exact date for when a canceled subscription is still active

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#75]
As a UX enhancement, we could (maybe?) determine how long a subscription is still valid for after cancellation. For example, an email might look like this:

Your subscription has been cancelled; you will not be billed again. However, you are paid up through June 30, 2016 so your subscription will remain active until then.

Enhancement to https://github.com/mozilla/payments/issues/77

**Comment by kumar303** [comment]
This was spec'ed out in the original cancelation UX: http://payments.readthedocs.org/en/latest/design/api/provider.html#subscription-cancelled

**Comment by brampitoyo** [comment]
mozilla/payments-service#77 has a design for when the end date is known (right side).

**Comment by andymckay** [comment]
I think this already there.
