### ISSUE TITLE
Create HTML email for subscription cancellation

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#77]
see this for the text version: https://github.com/mozilla/payments-service/pull/74

**Comment by brampitoyo** [comment]
Reference design:
![subscription-cancelled-email](https://cloud.githubusercontent.com/assets/51007/8245849/9c5f196e-15e9-11e5-830c-26eb947f1da3.png)

**Comment by andymckay-limited-access** [comment]
Those emails don't seem to be in the payments docs at http://payments.readthedocs.org/en/latest/, any chance we could add them?
