### ISSUE TITLE
Create HTML email for subscription charge failures

### ISSUE THREAD

**Issue by kumar303** [mozilla/payments-service#78]
text version of the email: https://github.com/mozilla/payments-service/pull/73

**Comment by brampitoyo** [comment]
Reference design:
![subscription-charge-failed-email](http://payments.readthedocs.org/en/latest/_images/ux-email-receipt-subscription-charge-failed.png)

**Comment by andymckay** [comment]
As per comments on https://github.com/mozilla/payments-service/pull/102#discussion-diff-34611261R15, whats the point of having the users email in there?
